# Generated by Django 2.2 on 2025-05-02 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20250429_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libroinstancia',
            name='estatus',
            field=models.CharField(blank=True, choices=[('m', 'Mantenimieno'), ('p', 'En prestamo'), ('d', 'Disponible'), ('r', 'Reservado')], default='m', help_text='Disponibilidad del libro', max_length=1),
        ),
    ]
