# Generated by Django 2.2 on 2025-05-05 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_auto_20250502_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='primernombre',
            new_name='nombre',
        ),
    ]
