# Generated by Django 2.2 on 2025-05-06 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_auto_20250505_0207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='genero',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='lenguaje',
            old_name='lenguaje',
            new_name='nombre',
        ),
    ]
