# Generated by Django 2.2 on 2025-06-19 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0005_auto_20250506_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido']},
        ),
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['titulo', 'autor']},
        ),
        migrations.AddField(
            model_name='libroinstancia',
            name='prestatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
